# Generated by Django 3.2.1 on 2021-05-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='upadted',
            new_name='updated',
        ),
    ]
