# Generated by Django 3.2.1 on 2021-05-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_upadted_article_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='media/images/default.jpg', null=True, upload_to='media/images/'),
        ),
    ]
